version: '1.0'
name: test
displayName: test
triggers:
  trigger: auto
  push:
    branches:
      prefix:
        - master
        - v1
        - v2
        - develop
stages:
  - name: golang-build-stage
    displayName: 'Golang Stage'
    strategy: naturally
    trigger: auto
    executor: []
    steps:
      - step: golangbuild@1
        name: olang-build
        displayName: Golang 构建
        golangVersion: '1.16'
        commands:
          - echo '执行任务' 
permissions:
  - role: admin
    members: []
